---
title: "Network analysis of alternative medicine attitudes"
author: "Szilvia Zörgő, Samvel Mkhitaryan & Gjalt-Jorn Peters"
date: "February 6, 2019"
html_document:
  self_contained: true
editor_options: 
  chunk_output_type: console
---

# Analyses

## Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE);

if (!'ufs' %in% row.names(installed.packages())) install.packages('ufs');
ufs::safeRequire('haven');
ufs::safeRequire('here');
ufs::safeRequire('pander');
ufs::safeRequire('GGally');
ufs::safeRequire('ggcorrplot');
ufs::safeRequire('userfriendlyscience');

dataPath <-
  here::here('data');

```

## Loading and preparing data

```{r import-data}

### Import using haven
dat <-
  haven::read_sav(file.path(dataPath,
                            'database.orig.new labels.sav'));

### ... But convert to a data frame instead of a tibble, because,
### for example, length(unique(dat[, 'group'])) results in 1 instead
### of 2...
dat <- as.data.frame(dat);
dat <- haven::zap_label(dat);
dat <- haven::zap_labels(dat);

### Set group as factor
dat$group <-
  factor(dat$group,
         levels=1:2,
         labels=c("Alternative medicine",
                  "Medicine"));

dat$group_tri <-
  ifelse(dat$group=="Medicine",
         1,
         ifelse(dat$TCM6_simult < 3,
                2,
                ifelse(dat$TCM6_simult > 2,
                       3,
                       NA)));

dat$group_tri <-
  factor(dat$group_tri,
         levels=1:3,
         labels=c("Biomed",
                  "Alternative",
                  "Complementary"));
         
### Extract and store attitude variable names
attitudeVars <-
  grep('ATT1_',
       names(dat),
       value=TRUE);

```

## Descriptives

```{r descriptives, fig.height=20}

ufs::cat0("\n\n### Group\n\n");
pander(userfriendlyscience::freq(dat$group));

ufs::cat0("\n\n### Missing values\n\n");
apply(is.na(dat[, attitudeVars]), 2, sum);

ufs::cat0("\n\n### Attitude\n\n");

ufs::meansComparisonDiamondPlot(dat,
                                rev(attitudeVars),
                                compareBy = 'group_tri',
                                comparisonColors = viridis::viridis(3,
                                                                    end=.7),
                                dataAlpha=.25);

```

## Correlations {.tabset .tabset-fade}

### All attitude variables together

```{r correlations-all, fig.width=18, fig.height=18}

### Takes way too long, huge, etc
# GGally::ggpairs(dat[, attitudeVars]);

cors <- cor(dat[, attitudeVars],
            use='complete.obs');

knitr::kable(cors);

### http://www.sthda.com/english/wiki/ggcorrplot-visualization-of-a-correlation-matrix-using-ggplot2
                
ggcorrplot::ggcorrplot(cors);

ggcorrplot::ggcorrplot(cors,
                       method = "circle");

ggcorrplot(cors,
           hc.order = TRUE,
           outline.col = "white")

ggcorrplot::ggcorrplot(cors,
                       lab = TRUE);

```

### Pairwise scatterplots {.tabset .tabset-fade .tabset-pills}

```{r correlations-pairwise, fig.width=6, fig.height=6, results="asis", eval=TRUE}

for (xAxisVar in attitudeVars) {

  ufs::cat0("\n\n#### ", xAxisVar,
            " {.tabset .tabset-fade .tabset-pills}\n\n");

  for (yAxisVar in tail(attitudeVars, -1)) {

    ### Only for 'half the matrix'
    if (which(attitudeVars == yAxisVar) >
        which(attitudeVars == xAxisVar)) {
      ufs::cat0("\n\n##### ", yAxisVar,
                "\n\n");
      print(ggplot2::ggplot(data=dat,
                            mapping=ggplot2::aes_string(x=xAxisVar,
                                                        y=yAxisVar,
                                                        color='group_tri')) +
              geom_jitter(size=3) +
              theme_minimal());
    }
  }
}

```


```{r network-analyses, fig.width=6, fig.height=6, results="asis", eval=TRUE}



```


